services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto_app
    restart: unless-stopped
    ports:
      - "7000:7000"
      - "50051:50051"
    env_file:
      - .env